### PR TITLE
discuss carthage protocol changes

### PR DESCRIPTION
**Pull request by amzid**
I am opening this PR to discuss if there are any changes needed for the carthage protocol:
* [RPC changes due to Carthage](https://tezos.gitlab.io/protocols/006_carthage.html#changes-to-the-binary-format-of-operations)
* [Tzstats changes](https://tzstats.com/blog/better-tezos-api-data-on-tzstats/)

The list of changes does not include breaking changes for the TRD. First tests on the carthagenet test blockchain using PRPC and tzstats result in successful identical batch payments.
After the protocol injection, new tests on the mainnet will be made to ensure the usability of the TRD for the new protocol and/or if there are any required changes.
Any issues regarding the compatibility with carthage can be reported here in this PR in order to adapt the code.

### CODE REVIEW

**Comment by jdsika** [comment]
@chiptus @utdrmac you guys have anything to add here? I would propose to quickly merge and create a tag "Carthage compatible"?

**Comment by utdrmac** [comment]
This is good for me. Yes, Carthage compatible.

**Comment by chiptus** [comment]
Not 100% sure what this pr is about. These are changes needed to use with carthage?

**Comment by utdrmac** [comment]
@chiptus No, no changes are needed to make TRD work on Carthage. I think the intent here is to merge these tiny changes and create a "release" of  TRD which is "Carthage Compatible" (just some marketing fluff)

**Comment by jdsika** [comment]
"marketing fluff" tztztztztz 

people need to know if it works and a tag gives them confidence that it is tested :)

**Pull request merged**
